In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

C:\Users\asus\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
#Setting random seed
np.random.seed(0)

In [79]:
iris = load_iris()

In [80]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   sepal length (cm)  150 non-null    float64 
 1   sepal width (cm)   150 non-null    float64 
 2   petal length (cm)  150 non-null    float64 
 3   petal width (cm)   150 non-null    float64 
 4   species            150 non-null    category
 5   is_train           150 non-null    bool    
dtypes: bool(1), category(1), float64(4)
memory usage: 5.2 KB


In [77]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [78]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
#Adding new column for species name
df['species'] = pd.Categorical.from_codes(iris.target,iris.target_names) #iris.target  will be conv to iris.targets_name

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [11]:
#Creating train and test data
df['is_train'] = np.random.uniform(0,1,len(df)) <= .75 #i.e here we are taking 75% of data as training data

In [13]:
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True  
5  setosa      True  
6  setosa      True  
7  setosa     False  
8  setosa     False  
9  setosa      True

In [14]:
#True --> Training data , False--> Testing data

In [15]:
#Creating dataframes from training rows and testing rows
df[df['is_train']==True] #df in which df['is_train'] == True

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
141                6.9               3.1                5.1               2.3   
142                5.8               2.7                5.1               1.9   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
148                6.2               3.4                5.4               2.3   

       species  is_train  
0       setosa      True  
1       setosa      True  
2       setosa      True  
3       setosa      True  
4       setosa      True  
..         ...       ...  
141  virginica      True  
142  virginica      True  
145  virginica      True  
146  virginica      True  
148  virginica      True  

[118 rows x 6 columns]

In [16]:
train, test = df[df['is_train']==True], df[df['is_train']== False] #Train and Test data


In [17]:
len(train)

118

In [18]:
len(test)

32

In [47]:
#Now craeting a list of features and lables that is X and y
features = df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [54]:
train['species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
141    virginica
142    virginica
145    virginica
146    virginica
148    virginica
Name: species, Length: 118, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [43]:
#Converting each species name of training data into digits(for computer to understand) 
y = pd.factorize(train['species'])[0] #We use [0] bcoz this is in the format of array of arrays

In [81]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [55]:
#Finally creaing our Random forest classifier model
model = RandomForestClassifier(n_jobs = 2,random_state=0) #n_jobs = 2 is a kind of default value when working on PC
model.fit(train[features],y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [61]:
#Prediction
model.predict(test[features]) #model predicts the species class type


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [60]:
#viewing the predicted probabilties of first 10 obs
model.predict_proba(test[features])[:10]

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [65]:
#Converting back the names of species from each predicted species class type
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [71]:
y_pred = iris.target_names[model.predict(test[features])]
y_pred

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica'],
      dtype='<U10')

In [72]:
#Viewing the actual species #i.e (y_test)
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [73]:
from sklearn.metrics import classification_report
print(classification_report(test['species'],y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        13
  versicolor       1.00      0.71      0.83         7
   virginica       0.86      1.00      0.92        12

    accuracy                           0.94        32
   macro avg       0.95      0.90      0.92        32
weighted avg       0.95      0.94      0.93        32



In [74]:
#Creating Confusion matrix
pd.crosstab(test['species'],y_pred,rownames=['Actual Species'],colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [87]:
#Prediction  for some unknown species by inputting its features
pred = iris.target_names[model.predict([[5.7,3.1,1.1,2.9],[5.7,3.1,1.1,2.9]])]
pred

array(['setosa', 'setosa'], dtype='<U10')

In [89]:
"""
#Steps we did:-
1.Load data
2.Dataframe of features and then add [species] and [is_train] column
3.Splitting of train and test data ,where training data is 0.75%
4.Creating train[features] and y i.e lables
5.Create a classifier model of RandomForestClassifier
6.Fitting train[features] and y into it
7.Prediction of test[features]
8.Evaluation and predicting unknown species for some given data
                                                            """

'\n#Steps we did:-\n1.Load data\n2.Dataframe of features and then add [species] and [is_train] column\n3.Splitting of train and test data ,where training data is 0.75%\n4.Creating train[features] and y i.e lables\n5.Create a classifier model of RandomForestClassifier\n6.Fitting train[features] and y into it\n7.Prediction of test[features]\n8.Evaluation and predicting unknown species for some given data\n                                                            '